all:
  vars:
    # Ensure Ansible uses Python 3 on Ubuntu CC images
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    node1:
      # Replace with the actual Terraform output for node1
      ansible_host: 192.168.1.11
      ansible_user: cc